# -*- coding: utf-8 -*-
"""Ekonomija_Section3_1_Sample characteristics and descriptive overview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5U4JCuXXZjV_dmQUCQvHSGJExonvPna
"""

import pandas as pd

putanja_descriptive_overview = "/content/Survey_Results.xlsx"

tablica_descriptive_overview = pd.read_excel(
    putanja_descriptive_overview,
    sheet_name="encoded_responses_corrected"
)

print(tablica_descriptive_overview.shape)
display(tablica_descriptive_overview.head())

import numpy as np

def make_frequency_table(df, cols, labels=None, total_n=None):
    if total_n is None:
        total_n = len(df)
    rows = []
    for col in cols:
        if col in df.columns:
            n = int(df[col].sum())
            rows.append({
                "variable": col,
                "category": labels.get(col, col) if labels else col,
                "n": n,
                "percent": round(n / total_n * 100, 2)
            })
    return (
        pd.DataFrame(rows)
        .sort_values(["n", "category"], ascending=[False, True])
        .reset_index(drop=True)
    )

def print_table(title, table):
    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)
    print(table.to_string(index=False))

labels = {
    # Gender
    "q01_spol__musko": "Male",
    "q01_spol__zensko": "Female",

    # Generation
    "q02_generacija__boomers": "Baby boomers",
    "q02_generacija__gen_x": "Gen X",
    "q02_generacija__gen_y": "Gen Y",
    "q02_generacija__gen_alpha": "Gen Alpha",
    "q02_generacija__other_selected": "Other",

    # Legal form
    "q03_pravni_oblik__doo_jdoo": "d.o.o./j.d.o.o.",
    "q03_pravni_oblik__javno_poduzece": "Public company",
    "q03_pravni_oblik__other_selected": "Other legal form",

    # Ownership
    "q05_organizacijska_struktura__hrvatsko_vlasnistvo": "Croatian ownership",
    "q05_organizacijska_struktura__uglavnom_hrvatsko": "Mostly Croatian ownership",
    "q05_organizacijska_struktura__mijesano_50_50": "Mixed Croatian/foreign ownership",
    "q05_organizacijska_struktura__uglavnom_strano": "Mostly foreign ownership",
    "q05_organizacijska_struktura__strano_vlasnistvo": "Foreign ownership",

    # Firm size
    "q08_velicina_subjekta__mikro": "Micro",
    "q08_velicina_subjekta__mali": "Small",
    "q08_velicina_subjekta__srednji": "Medium",
    "q08_velicina_subjekta__veliki": "Large",

    # Sector
    "q09_sektor__administrativne_i_usluzne_djelatnosti": "Administrative and support service activities",
    "q09_sektor__rudarstvo": "Mining and quarrying",
    "q09_sektor__ostale_usluge": "Other service activities",
    "q09_sektor__gradjevina": "Construction",
    "q09_sektor__proizvodnja": "Manufacturing",
    "q09_sektor__zdravlje_i_socijalni_rad": "Human health and social work",
    "q09_sektor__kucna_radinost_ili_obiteljsko_poljoprivredno": "Cottage industry / family agricultural business",
    "q09_sektor__informacije_i_komunikacije": "Information and communication",
    "q09_sektor__nekretnine": "Real estate activities",
    "q09_sektor__trgovina": "Wholesale and retail trade",
    "q09_sektor__osiguranje": "Insurance",
    "q09_sektor__umjetnost_zabava_slobodno_vrijeme": "Arts, entertainment and recreation",
    "q09_sektor__poljoprivreda_sumarstvo_ribarstvo": "Agriculture, forestry and fishing",
    "q09_sektor__obrazovanje": "Education",
    "q09_sektor__financijske_usluge": "Financial services",
    "q09_sektor__profesionalne_tehnicke_usluge": "Professional and technical services",
    "q09_sektor__usluge_smjestaja": "Accommodation services",
    "q09_sektor__dostava_skladistenje": "Transportation and storage",
    "q09_sektor__extraterritorial_organization": "Extraterritorial organization",
    "q09_sektor__energenti": "Energy",
    "q09_sektor__upravljanje_vodama": "Water management",
    "q09_sektor__other_selected": "Other sector",

    # Measurable indicators
    "q10_mjerljivi_indikatori__da": "Yes",
    "q10_mjerljivi_indikatori__ne": "No",

    # Sustainability in strategy
    "q14_odrzivost_u_strategiji__da": "Yes",
    "q14_odrzivost_u_strategiji__ne": "No",

    # Standards / CSR
    "q19_elementi_odrzivosti__iso_9001": "ISO 9001",
    "q19_elementi_odrzivosti__iso_14001": "ISO 14001",
    "q19_elementi_odrzivosti__ciljevi_drustvene_odgovornosti": "CSR goals / activities",
    "q19_elementi_odrzivosti__nista_od_navedenog": "None of the listed",

    # Sustainability measurement
    "q24_mjerenje_ciljeva_odrzivosti__da": "Yes",
    "q24_mjerenje_ciljeva_odrzivosti__ne": "No",

    # Sustainability position
    "q26_najvisa_pozicija_za_odrzivost__top_menadzment": "Top management",
    "q26_najvisa_pozicija_za_odrzivost__srednji_menadzment": "Middle management",
    "q26_najvisa_pozicija_za_odrzivost__odjel_menadzmenta": "Management department",
    "q26_najvisa_pozicija_za_odrzivost__menadzer": "Manager",
    "q26_najvisa_pozicija_za_odrzivost__vlasnik": "Owner",
    "q26_najvisa_pozicija_za_odrzivost__subordinate": "Subordinate",
    "q26_najvisa_pozicija_za_odrzivost__nema_pozicije": "No such position",

    # SDG awareness
    "q35_culi_za_un_sdg__da": "Yes",
    "q35_culi_za_un_sdg__ne": "No",
}


n_firms = len(tablica_descriptive_overview)
n_columns = tablica_descriptive_overview.shape[1]

sample_overview = pd.DataFrame([
    {"measure": "Number of analysed firms/respondents", "value": n_firms},
    {"measure": "Number of encoded variables in the dataset", "value": n_columns},
])

print_table("1. Number of analysed firms/respondents", sample_overview)


gender_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q01_spol__")]
generation_cols = [
    c for c in tablica_descriptive_overview.columns
    if c.startswith("q02_generacija__") and not c.endswith("__other_text")
]

gender_table = make_frequency_table(tablica_descriptive_overview, gender_cols, labels, n_firms)
generation_table = make_frequency_table(tablica_descriptive_overview, generation_cols, labels, n_firms)

print_table("2.1 Gender of owner/manager", gender_table)
print_table("2.2 Generation of owner/manager", generation_table)


legal_form_cols = [
    c for c in tablica_descriptive_overview.columns
    if c.startswith("q03_pravni_oblik__") and not c.endswith("__other_text")
]
ownership_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q05_organizacijska_struktura__")]
firm_size_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q08_velicina_subjekta__")]
sector_cols = [
    c for c in tablica_descriptive_overview.columns
    if c.startswith("q09_sektor__") and not c.endswith("__other_text")
]

legal_form_table = make_frequency_table(tablica_descriptive_overview, legal_form_cols, labels, n_firms)
ownership_table = make_frequency_table(tablica_descriptive_overview, ownership_cols, labels, n_firms)
firm_size_table = make_frequency_table(tablica_descriptive_overview, firm_size_cols, labels, n_firms)
sector_table = make_frequency_table(tablica_descriptive_overview, sector_cols, labels, n_firms)

numeric_structural_cols = ["q06_godina_osnutka", "q07_broj_zaposlenika"]
numeric_structural_summary = tablica_descriptive_overview[numeric_structural_cols].describe().T
numeric_structural_summary["median"] = tablica_descriptive_overview[numeric_structural_cols].median()
numeric_structural_summary = numeric_structural_summary[
    ["count", "mean", "std", "min", "25%", "median", "50%", "75%", "max"]
].round(3)

tablica_descriptive_overview["company_age"] = 2025 - tablica_descriptive_overview["q06_godina_osnutka"]
tablica_descriptive_overview["log_employees"] = np.log1p(tablica_descriptive_overview["q07_broj_zaposlenika"])

numeric_derived_summary = tablica_descriptive_overview[["company_age", "log_employees"]].describe().T
numeric_derived_summary["median"] = tablica_descriptive_overview[["company_age", "log_employees"]].median()
numeric_derived_summary = numeric_derived_summary[
    ["count", "mean", "std", "min", "25%", "median", "50%", "75%", "max"]
].round(3)

print_table("3.1 Legal form", legal_form_table)
print_table("3.2 Ownership structure", ownership_table)
print_table("3.3 Year of foundation and number of employees", numeric_structural_summary.reset_index().rename(columns={"index": "variable"}))
print_table("3.4 Derived numeric characteristics: company age and log employees", numeric_derived_summary.reset_index().rename(columns={"index": "variable"}))
print_table("3.5 Firm size", firm_size_table)
print_table("3.6 Sector", sector_table)


measurable_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q10_mjerljivi_indikatori__")]
strategy_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q14_odrzivost_u_strategiji__")]
standards_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q19_elementi_odrzivosti__")]
measurement_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q24_mjerenje_ciljeva_odrzivosti__")]
position_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q26_najvisa_pozicija_za_odrzivost__")]
awareness_cols = [c for c in tablica_descriptive_overview.columns if c.startswith("q35_culi_za_un_sdg__")]

measurable_table = make_frequency_table(tablica_descriptive_overview, measurable_cols, labels, n_firms)
strategy_table = make_frequency_table(tablica_descriptive_overview, strategy_cols, labels, n_firms)
standards_table = make_frequency_table(tablica_descriptive_overview, standards_cols, labels, n_firms)
measurement_table = make_frequency_table(tablica_descriptive_overview, measurement_cols, labels, n_firms)
position_table = make_frequency_table(tablica_descriptive_overview, position_cols, labels, n_firms)
awareness_table = make_frequency_table(tablica_descriptive_overview, awareness_cols, labels, n_firms)

positive_standard_cols = [
    "q19_elementi_odrzivosti__iso_9001",
    "q19_elementi_odrzivosti__iso_14001",
    "q19_elementi_odrzivosti__ciljevi_drustvene_odgovornosti",
]
tablica_descriptive_overview["Has_quality_or_sustainability_standard"] = (
    tablica_descriptive_overview[positive_standard_cols].sum(axis=1) > 0
).astype(int)

tablica_descriptive_overview["Has_sustainability_position"] = (
    1 - tablica_descriptive_overview["q26_najvisa_pozicija_za_odrzivost__nema_pozicije"]
)

sustainability_key_summary = pd.DataFrame([
    {
        "characteristic": "Has measurable business indicators",
        "n_yes": int(tablica_descriptive_overview["q10_mjerljivi_indikatori__da"].sum()),
        "percent_yes": round(tablica_descriptive_overview["q10_mjerljivi_indikatori__da"].mean() * 100, 2)
    },
    {
        "characteristic": "Sustainability included in mission/vision/strategy/goals",
        "n_yes": int(tablica_descriptive_overview["q14_odrzivost_u_strategiji__da"].sum()),
        "percent_yes": round(tablica_descriptive_overview["q14_odrzivost_u_strategiji__da"].mean() * 100, 2)
    },
    {
        "characteristic": "Has at least one quality/sustainability standard or CSR element",
        "n_yes": int(tablica_descriptive_overview["Has_quality_or_sustainability_standard"].sum()),
        "percent_yes": round(tablica_descriptive_overview["Has_quality_or_sustainability_standard"].mean() * 100, 2)
    },
    {
        "characteristic": "Measures sustainability goals",
        "n_yes": int(tablica_descriptive_overview["q24_mjerenje_ciljeva_odrzivosti__da"].sum()),
        "percent_yes": round(tablica_descriptive_overview["q24_mjerenje_ciljeva_odrzivosti__da"].mean() * 100, 2)
    },
    {
        "characteristic": "Has sustainability-related position",
        "n_yes": int(tablica_descriptive_overview["Has_sustainability_position"].sum()),
        "percent_yes": round(tablica_descriptive_overview["Has_sustainability_position"].mean() * 100, 2)
    },
    {
        "characteristic": "Prior awareness of UN SDGs",
        "n_yes": int(tablica_descriptive_overview["q35_culi_za_un_sdg__da"].sum()),
        "percent_yes": round(tablica_descriptive_overview["q35_culi_za_un_sdg__da"].mean() * 100, 2)
    },
])

print_table("4.1 Measurable business indicators", measurable_table)
print_table("4.2 Sustainability in strategy", strategy_table)
print_table("4.3 Sustainability standards / CSR elements", standards_table)
print_table("4.4 Sustainability goal measurement", measurement_table)
print_table("4.5 Sustainability-related position", position_table)
print_table("4.6 Prior awareness of UN SDGs", awareness_table)
print_table("4.7 Key sustainability-related characteristics summary", sustainability_key_summary)


sdg_direct_cols = [
    col for col in tablica_descriptive_overview.columns
    if col.startswith("q37_sdg_vezani_uz_poslovanje__")
    and col != "q37_sdg_vezani_uz_poslovanje__none_directly_related"
]

none_sdg_col = "q37_sdg_vezani_uz_poslovanje__none_directly_related"

tablica_descriptive_overview["SDG_count"] = tablica_descriptive_overview[sdg_direct_cols].sum(axis=1)

if none_sdg_col in tablica_descriptive_overview.columns:
    tablica_descriptive_overview.loc[tablica_descriptive_overview[none_sdg_col] == 1, "SDG_count"] = 0

tablica_descriptive_overview["SDG_involvement_level"] = pd.cut(
    tablica_descriptive_overview["SDG_count"],
    bins=[-1, 1, 4, 17],
    labels=[
        "Low SDG involvement, 0-1",
        "Moderate SDG involvement, 2-4",
        "High SDG involvement, 5+"
    ]
)

sdg_count_summary = tablica_descriptive_overview["SDG_count"].describe().to_frame().T
sdg_count_summary["median"] = tablica_descriptive_overview["SDG_count"].median()
sdg_count_summary = sdg_count_summary[
    ["count", "mean", "std", "min", "25%", "median", "50%", "75%", "max"]
].round(3)

sdg_level_table = (
    tablica_descriptive_overview["SDG_involvement_level"]
    .value_counts()
    .sort_index()
    .rename_axis("SDG involvement level")
    .reset_index(name="n")
)
sdg_level_table["percent"] = (sdg_level_table["n"] / n_firms * 100).round(2)

print_table("5.1 Initial overview of SDG_count", sdg_count_summary.reset_index(drop=True))
print_table("5.2 SDG involvement levels", sdg_level_table)



output_path_descriptive_overview = "/content/chapter_sample_characteristics.xlsx"

with pd.ExcelWriter(output_path_descriptive_overview, engine="openpyxl") as writer:
    sample_overview.to_excel(writer, sheet_name="sample_overview", index=False)
    gender_table.to_excel(writer, sheet_name="gender", index=False)
    generation_table.to_excel(writer, sheet_name="generation", index=False)
    legal_form_table.to_excel(writer, sheet_name="legal_form", index=False)
    ownership_table.to_excel(writer, sheet_name="ownership", index=False)
    numeric_structural_summary.to_excel(writer, sheet_name="numeric_structural")
    numeric_derived_summary.to_excel(writer, sheet_name="numeric_derived")
    firm_size_table.to_excel(writer, sheet_name="firm_size", index=False)
    sector_table.to_excel(writer, sheet_name="sector", index=False)
    measurable_table.to_excel(writer, sheet_name="measurable_indicators", index=False)
    strategy_table.to_excel(writer, sheet_name="sustainability_strategy", index=False)
    standards_table.to_excel(writer, sheet_name="standards_CSR", index=False)
    measurement_table.to_excel(writer, sheet_name="sustainability_measure", index=False)
    position_table.to_excel(writer, sheet_name="sustainability_position", index=False)
    awareness_table.to_excel(writer, sheet_name="SDG_awareness", index=False)
    sustainability_key_summary.to_excel(writer, sheet_name="sustainability_summary", index=False)
    sdg_count_summary.to_excel(writer, sheet_name="SDG_count_summary", index=False)
    sdg_level_table.to_excel(writer, sheet_name="SDG_levels", index=False)

print("\n" + "=" * 100)
print("Spremljen Excel izvještaj za poglavlje sample_characteristics:")
print(output_path_descriptive_overview)